### PR TITLE
Add param to change filter levels

### PR DESCRIPTION
**Pull request by mintar**
This feature was added in royale 3.21, so pico_flexx_driver now requires
at least this version.

See: https://pmdtec.com/picofamily/2019/02/22/royale_release_v321/

The new filter level "Full" includes some additional filters (i.e.
smoothing, hole filling etc.) that improve the depth image smoothness.

### CODE REVIEW

**Comment by mintar** [comment]
I'm not 100% sure if we should merge this pull request. The new functions that I'm calling here (`setFilterLevel`, `getFilterLevel`) have been introduced in the royale SDK 3.21 (the newest one), so compilation will break if used with an older version of royale. Unfortunately, royale doesn't provide version defines (AFAIK), so I cannot wrap the new functions in `#ifdef`s.

@amaldo , @jspricke : Any thoughts? Should we merge anyway, and hope people will figure out that they have to use the newest royale SDK?

**Comment by mintar** [comment]
Ubuntu Trusty (= ROS Indigo) requires royale <= 3.11 (see #18), so if we now require royale >= 3.21, that means the pico_flexx_driver doesn't run on Trusty from this point on.

**Comment by jspricke** [comment]
my libroyale contains a `royale-config.cmake` with `SET(royale_VERSION 3.20.0)` (plus version parts).

**Comment by mintar** [comment]
Thanks @jspricke , I somehow missed that. I've updated the PR and will merge now.

**Pull request merged**
